//------------------------------------------------------------------------------
// File    : axi_scoreboard.sv
// Author  : ken, Lu Wei-Ru
// Created : 2026-01-18
// Brief   : AXI4 scoreboard that compares observed (ACT) transactions from the
//           monitor against expected (EXP) transactions from the reference model.
//           Supports in-order queue compare (M0/M1) and optional ID/tag-based
//           matching for out-of-order returns (M2).
//------------------------------------------------------------------------------
//
// Notes:
// - ACT comes from monitor (analysis port).
// - EXP is generated by cloning ACT and calling ref_model.predict().
// - M0/M1: compare in-order using FIFO queues.
// - M2   : optional out-of-order matching by ID (and future tag).
//------------------------------------------------------------------------------

`ifndef _AXI_SCOREBOARD_SV_
`define _AXI_SCOREBOARD_SV_

class axi_scoreboard extends uvm_component;
  `uvm_component_utils(axi_scoreboard)

  // Analysis input from monitor
  uvm_analysis_imp #(axi_seq_item, axi_scoreboard) act_imp;

  // Reference model
  axi_ref_model rm;

  // -------------------------
  // Mode control
  // -------------------------
  bit enable_ooo_match = 0;   // M2 off by default (M0/M1 on)
  bit verbose          = 0;

  // -------------------------
  // M0/M1: in-order queues
  // -------------------------
  axi_seq_item act_q[$];
  axi_seq_item exp_q[$];

  // -------------------------
  // M2: out-of-order by ID
  // - Keep both ACT and EXP queues per ID
  // - Compare in arrival order within same ID
  // -------------------------
  axi_seq_item act_by_id[int unsigned][$];
  axi_seq_item exp_by_id[int unsigned][$];

  // stats
  int unsigned pass_cnt = 0;
  int unsigned fail_cnt = 0;

  extern function new(string name="axi_scoreboard", uvm_component parent=null);
  extern virtual function void build_phase(uvm_phase phase);
  extern virtual function void report_phase(uvm_phase phase);

  // analysis write() callback
  extern function void write(axi_seq_item act_tr);

  // compare helpers
  extern function void gen_expected_from_act(input axi_seq_item act_tr,
                                             output axi_seq_item exp_tr);
  extern function bit compare_pair(input axi_seq_item act_tr,
                                   input axi_seq_item exp_tr);
  extern function void try_compare_in_order();
  extern function void try_compare_ooo_by_id(input int unsigned id_key);

endclass : axi_scoreboard

function axi_scoreboard::new(string name="axi_scoreboard", uvm_component parent=null);
  super.new(name, parent);
  act_imp = new("act_imp", this);
endfunction

function void axi_scoreboard::build_phase(uvm_phase phase);
  super.build_phase(phase);

  rm = axi_ref_model::type_id::create("rm");

  // Optional: set RM knobs from config_db if you want later
  // rm.configure(`AXI_DEFAULT_BASE_ADDR, `AXI_DEFAULT_MEM_BYTES, 1'b1, 1'b1, 1'b0);
endfunction

function void axi_scoreboard::report_phase(uvm_phase phase);
  super.report_phase(phase);
  `uvm_info(get_type_name(),
            $sformatf("SCOREBOARD SUMMARY: PASS=%0d FAIL=%0d", pass_cnt, fail_cnt),
            UVM_NONE)
endfunction

//------------------------------------------------------------------------------
// Generate EXP by cloning ACT then calling ref_model.predict()
//------------------------------------------------------------------------------
function void axi_scoreboard::gen_expected_from_act(input axi_seq_item act_tr,
                                                    output axi_seq_item exp_tr);
  exp_tr = axi_seq_item::type_id::create("exp_tr");

  // Copy request fields
  exp_tr.rw    = act_tr.rw;
  exp_tr.id    = act_tr.id;
  exp_tr.addr  = act_tr.addr;
  exp_tr.len   = act_tr.len;
  exp_tr.size  = act_tr.size;
  exp_tr.burst = act_tr.burst;

  exp_tr.beats = int'(exp_tr.len) + 1;
  if (exp_tr.beats == 0) exp_tr.beats = 1;

  // Copy / allocate payload
  if (exp_tr.rw == AXI_WRITE) begin
    exp_tr.wdata = new[act_tr.wdata.size()];
    exp_tr.wstrb = new[act_tr.wstrb.size()];
    foreach (act_tr.wdata[i]) exp_tr.wdata[i] = act_tr.wdata[i];
    foreach (act_tr.wstrb[i]) exp_tr.wstrb[i] = act_tr.wstrb[i];
    exp_tr.rdata = new[0];
  end else begin
    exp_tr.rdata = new[exp_tr.beats]; // filled by predict()
    exp_tr.wdata = new[0];
    exp_tr.wstrb = new[0];
  end

  // Stall fields are for coverage only; keep same values (optional)
  exp_tr.aw_wait = act_tr.aw_wait;
  exp_tr.w_wait  = act_tr.w_wait;
  exp_tr.b_wait  = act_tr.b_wait;
  exp_tr.ar_wait = act_tr.ar_wait;
  exp_tr.r_wait  = act_tr.r_wait;

  // Predict response + data / mirror update
  rm.predict(exp_tr);
endfunction

//------------------------------------------------------------------------------
// Analysis write: receive ACT, create EXP, enqueue, then compare
//------------------------------------------------------------------------------
function void axi_scoreboard::write(axi_seq_item act_tr);
  axi_seq_item exp_tr;
  int unsigned id_key;

  gen_expected_from_act(act_tr, exp_tr);
  id_key = int'(act_tr.id);

  if (!enable_ooo_match) begin
    // M0/M1: FIFO compare
    act_q.push_back(act_tr);
    exp_q.push_back(exp_tr);

    if (verbose) begin
      `uvm_info(get_type_name(),
        $sformatf("SB(M0/M1): push ACT/EXP rw=%0d id=0x%0h addr=0x%0h len=%0d q=%0d",
                  act_tr.rw, act_tr.id, act_tr.addr, act_tr.len, act_q.size()),
        UVM_MEDIUM)
    end

    try_compare_in_order();
  end else begin
    // M2: OOO compare by ID (buffer both sides)
    act_by_id[id_key].push_back(act_tr);
    exp_by_id[id_key].push_back(exp_tr);

    if (verbose) begin
      `uvm_info(get_type_name(),
        $sformatf("SB(M2): push id=0x%0h act_q=%0d exp_q=%0d",
                  act_tr.id, act_by_id[id_key].size(), exp_by_id[id_key].size()),
        UVM_MEDIUM)
    end

    try_compare_ooo_by_id(id_key);
  end
endfunction

//------------------------------------------------------------------------------
// In-order compare (M0/M1)
//------------------------------------------------------------------------------
function void axi_scoreboard::try_compare_in_order();
  while (act_q.size() > 0 && exp_q.size() > 0) begin
    axi_seq_item act_tr = act_q.pop_front();
    axi_seq_item exp_tr = exp_q.pop_front();
    void'(compare_pair(act_tr, exp_tr));
  end
endfunction

//------------------------------------------------------------------------------
// Out-of-order compare by ID (M2)
//------------------------------------------------------------------------------
function void axi_scoreboard::try_compare_ooo_by_id(input int unsigned id_key);
  while (act_by_id.exists(id_key) && exp_by_id.exists(id_key) &&
         (act_by_id[id_key].size() > 0) && (exp_by_id[id_key].size() > 0)) begin
    axi_seq_item act_tr = act_by_id[id_key].pop_front();
    axi_seq_item exp_tr = exp_by_id[id_key].pop_front();
    void'(compare_pair(act_tr, exp_tr));
  end
endfunction

//------------------------------------------------------------------------------
// Compare one ACT vs EXP
//------------------------------------------------------------------------------
function bit axi_scoreboard::compare_pair(input axi_seq_item act_tr,
                                          input axi_seq_item exp_tr);
  bit ok = 1'b1;

  // Basic request fields sanity (optional but useful)
  if (act_tr.rw    !== exp_tr.rw)    ok = 1'b0;
  if (act_tr.id    !== exp_tr.id)    ok = 1'b0;
  if (act_tr.addr  !== exp_tr.addr)  ok = 1'b0;
  if (act_tr.len   !== exp_tr.len)   ok = 1'b0;
  if (act_tr.size  !== exp_tr.size)  ok = 1'b0;
  if (act_tr.burst !== exp_tr.burst) ok = 1'b0;

  // Compare response
  if (act_tr.resp !== exp_tr.resp) ok = 1'b0;

  // Compare read data if READ
  if (act_tr.rw == AXI_READ) begin
    if (act_tr.rdata.size() != exp_tr.rdata.size()) begin
      ok = 1'b0;
    end else begin
      foreach (act_tr.rdata[i]) begin
        if (act_tr.rdata[i] !== exp_tr.rdata[i]) ok = 1'b0;
      end
    end
  end

  if (ok) begin
    pass_cnt++;
    if (verbose) begin
      `uvm_info(get_type_name(),
        $sformatf("PASS: %s", act_tr.convert2string()),
        UVM_LOW)
    end
  end else begin
    fail_cnt++;
    `uvm_error(get_type_name(),
      $sformatf("FAIL:\n  ACT: %s\n  EXP: %s",
                act_tr.convert2string(), exp_tr.convert2string()))

    if (act_tr.rw == AXI_READ) begin
      int unsigned n;
      n = (act_tr.rdata.size() < exp_tr.rdata.size()) ? act_tr.rdata.size() : exp_tr.rdata.size();
      for (int unsigned i = 0; i < n; i++) begin
        if (act_tr.rdata[i] !== exp_tr.rdata[i]) begin
          `uvm_error(get_type_name(),
            $sformatf("  RDATA mismatch beat[%0d]: ACT=0x%0h EXP=0x%0h",
                      i, act_tr.rdata[i], exp_tr.rdata[i]))
        end
      end
    end
  end

  return ok;
endfunction

`endif // _AXI_SCOREBOARD_SV_
